# Generated by Django 3.0.5 on 2020-05-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatternType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatternBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, verbose_name='Паттерн')),
                ('pattern_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern', related_query_name='related_set', to='patern.PatternType')),
            ],
        ),
    ]
