# Generated by Django 3.0.5 on 2020-05-10 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patern', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternbody',
            name='pattern_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_b', to='patern.PatternType'),
        ),
    ]
