# Generated by Django 3.0.5 on 2020-05-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playeraudit',
            old_name='currency',
            new_name='curency',
        ),
        migrations.AlterField(
            model_name='playeraudit',
            name='action_type',
            field=models.CharField(default='NAN', max_length=20),
        ),
    ]
