# Generated by Django 3.0.5 on 2020-05-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_playeraudit_parse_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeraudit',
            name='parse_date',
        ),
    ]
